"""
Base strategy interface for all trading strategies.
Defines the common interface that all strategies must implement.
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional, Tuple
import pandas as pd
from enum import Enum
from dataclasses import dataclass
from datetime import time


class MarketType(Enum):
    """Market types supported by strategies."""
    EQUITY = "equity"
    FUTURES = "futures"
    OPTIONS = "options"
    COMMODITY = "commodity"
    CURRENCY = "currency"


class TimeFrame(Enum):
    """Timeframes supported by strategies."""
    TICK = "tick"
    MINUTE_1 = "1m"
    MINUTE_3 = "3m"
    MINUTE_5 = "5m"
    MINUTE_15 = "15m"
    MINUTE_30 = "30m"
    HOUR_1 = "1h"
    HOUR_4 = "4h"
    DAILY = "1d"
    WEEKLY = "1w"
    MONTHLY = "1M"


@dataclass
class MarketSession:
    """Indian market session timings."""
    PRE_OPEN_START = time(9, 0)
    PRE_OPEN_END = time(9, 15)
    MARKET_OPEN = time(9, 15)
    MARKET_CLOSE = time(15, 30)
    POST_MARKET_START = time(15, 40)
    POST_MARKET_END = time(16, 0)


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    action: str  # "BUY", "SELL", "HOLD"
    strength: float  # 0.0 to 1.0
    price: float
    timestamp: pd.Timestamp
    reason: str
    confidence: float = 0.5
    stop_loss: Optional[float] = None
    target: Optional[float] = None


@dataclass
class StrategyParams:
    """Base parameters for all strategies."""
    symbol: str
    quantity: int = 1
    risk_per_trade: float = 0.02  # 2% risk per trade
    max_positions: int = 1
    enabled: bool = True


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    All strategies must inherit from this class and implement required methods.
    """
    
    def __init__(self, params: Dict[str, Any]):
        self.params = params
        self.name = self.__class__.__name__
        self.timeframe = self.get_timeframe()
        self.market_type = self.get_market_type()
        self.indicators_cache = {}
        self.signals_history = []
        
    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name."""
        pass
    
    @abstractmethod
    def get_timeframe(self) -> TimeFrame:
        """Return the primary timeframe for this strategy."""
        pass
    
    @abstractmethod
    def get_market_type(self) -> MarketType:
        """Return the market type this strategy is designed for."""
        pass
    
    @abstractmethod
    def get_default_params(self) -> Dict[str, Any]:
        """Return default parameters for this strategy."""
        pass
    
    @abstractmethod
    def indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate and add technical indicators to the dataframe.
        
        Args:
            df: OHLCV dataframe
            
        Returns:
            DataFrame with indicators added as new columns
        """
        pass
    
    @abstractmethod
    def generate_signals(self, df: pd.DataFrame) -> List[Signal]:
        """
        Generate trading signals based on the data and indicators.
        
        Args:
            df: OHLCV dataframe with indicators
            
        Returns:
            List of trading signals
        """
        pass
    
    @abstractmethod
    def should_enter(self, df: pd.DataFrame, current_idx: int) -> Tuple[bool, str]:
        """
        Determine if we should enter a trade at the current bar.
        
        Args:
            df: OHLCV dataframe with indicators
            current_idx: Current bar index
            
        Returns:
            Tuple of (should_enter, reason)
        """
        pass
    
    @abstractmethod
    def should_exit(self, df: pd.DataFrame, current_idx: int, entry_price: float, 
                   entry_time: pd.Timestamp) -> Tuple[bool, str]:
        """
        Determine if we should exit a trade at the current bar.
        
        Args:
            df: OHLCV dataframe with indicators
            current_idx: Current bar index
            entry_price: Price at which we entered
            entry_time: Time at which we entered
            
        Returns:
            Tuple of (should_exit, reason)
        """
        pass
    
    @abstractmethod
    def get_stoploss(self, df: pd.DataFrame, current_idx: int, entry_price: float) -> float:
        """
        Calculate stop loss price for the current position.
        
        Args:
            df: OHLCV dataframe with indicators
            current_idx: Current bar index
            entry_price: Price at which we entered
            
        Returns:
            Stop loss price
        """
        pass
    
    @abstractmethod
    def get_target(self, df: pd.DataFrame, current_idx: int, entry_price: float) -> float:
        """
        Calculate target price for the current position.
        
        Args:
            df: OHLCV dataframe with indicators
            current_idx: Current bar index
            entry_price: Price at which we entered
            
        Returns:
            Target price
        """
        pass
    
    def is_market_open(self, timestamp: pd.Timestamp) -> bool:
        """Check if market is open at given timestamp."""
        market_time = timestamp.time()
        return MarketSession.MARKET_OPEN <= market_time <= MarketSession.MARKET_CLOSE
    
    def is_pre_market(self, timestamp: pd.Timestamp) -> bool:
        """Check if it's pre-market hours."""
        market_time = timestamp.time()
        return MarketSession.PRE_OPEN_START <= market_time < MarketSession.MARKET_OPEN
    
    def is_post_market(self, timestamp: pd.Timestamp) -> bool:
        """Check if it's post-market hours."""
        market_time = timestamp.time()
        return MarketSession.POST_MARKET_START <= market_time <= MarketSession.POST_MARKET_END
    
    def validate_params(self) -> bool:
        """Validate strategy parameters."""
        required_params = ['symbol']
        for param in required_params:
            if param not in self.params:
                return False
        return True
    
    def get_param(self, key: str, default: Any = None) -> Any:
        """Get parameter value with default fallback."""
        return self.params.get(key, default)
    
    def add_signal(self, signal: Signal) -> None:
        """Add signal to history."""
        self.signals_history.append(signal)
        # Keep only last 1000 signals
        if len(self.signals_history) > 1000:
            self.signals_history = self.signals_history[-1000:]
    
    def get_recent_signals(self, count: int = 10) -> List[Signal]:
        """Get recent signals."""
        return self.signals_history[-count:] if self.signals_history else []
    
    def __str__(self) -> str:
        return f"{self.name}({self.timeframe.value}, {self.market_type.value})"
    
    def __repr__(self) -> str:
        return self.__str__()