"""
AI Strategy Generator that creates and evolves trading strategies.
Uses machine learning to discover new trading patterns and strategies.
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Dict, List, Optional, Tuple, Any, Callable
import structlog
from dataclasses import dataclass, field
import json
import random
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

from ..core.models import TradingSignal, TradeDecision, Position, OrderSide
from ..strategy.base import Strategy, MarketContext, StrategyConfig
from .feature_engineering import FeatureEngineer, MarketFeatures

logger = structlog.get_logger(__name__)


@dataclass
class StrategyGene:
    """Genetic representation of a trading strategy."""
    # Entry conditions
    entry_indicators: List[str] = field(default_factory=list)
    entry_thresholds: Dict[str, float] = field(default_factory=dict)
    entry_logic: str = "AND"  # AND, OR, WEIGHTED
    
    # Exit conditions
    exit_indicators: List[str] = field(default_factory=list)
    exit_thresholds: Dict[str, float] = field(default_factory=dict)
    stop_loss_pct: float = 0.02
    take_profit_pct: float = 0.04
    
    # Position sizing
    position_size_method: str = "fixed"  # fixed, volatility_adjusted, kelly
    base_position_size: float = 0.1
    
    # Risk management
    max_positions: int = 3
    max_drawdown: float = 0.1
    
    # Time constraints
    max_hold_time: int = 24  # hours
    min_hold_time: int = 1   # hours
    
    # Market conditions
    preferred_volatility: Tuple[float, float] = (0.01, 0.05)
    preferred_volume: float = 1.5  # multiple of average
    
    # Performance metrics
    fitness_score: float = 0.0
    sharpe_ratio: float = 0.0
    win_rate: float = 0.0
    total_trades: int = 0
    
    def mutate(self, mutation_rate: float = 0.1):
        """Mutate the strategy gene."""
        if random.random() < mutation_rate:
            # Mutate thresholds
            for indicator in self.entry_thresholds:
                if random.random() < 0.3:
                    self.entry_thresholds[indicator] *= random.uniform(0.8, 1.2)
            
            # Mutate position sizing
            if random.random() < 0.2:
                self.base_position_size *= random.uniform(0.8, 1.2)
                self.base_position_size = max(0.05, min(0.3, self.base_position_size))
            
            # Mutate risk parameters
            if random.random() < 0.2:
                self.stop_loss_pct *= random.uniform(0.8, 1.2)
                self.take_profit_pct *= random.uniform(0.8, 1.2)


@dataclass
class StrategyPerformance:
    """Performance metrics for a generated strategy."""
    total_return: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    total_trades: int = 0
    avg_trade_duration: float = 0.0
    volatility: float = 0.0
    
    def calculate_fitness(self) -> float:
        """Calculate overall fitness score."""
        # Weighted combination of metrics
        fitness = (
            self.sharpe_ratio * 0.3 +
            self.total_return * 0.25 +
            self.win_rate * 0.2 +
            (1 - self.max_drawdown) * 0.15 +
            min(self.profit_factor / 2, 1.0) * 0.1
        )
        return max(0, fitness)


class GeneratedStrategy(Strategy):
    """A strategy generated by the AI strategy generator."""
    
    def __init__(self, strategy_config: StrategyConfig, gene: StrategyGene, feature_engineer: FeatureEngineer):
        super().__init__(strategy_config)
        self.gene = gene
        self.feature_engineer = feature_engineer
        self.ml_model = None
        self.scaler = StandardScaler()
        self.is_trained = False
        
        # Override base parameters with gene values
        self.max_positions = gene.max_positions
        self.position_size_pct = gene.base_position_size
        self.stop_loss_pct = gene.stop_loss_pct
        self.take_profit_pct = gene.take_profit_pct
        
        logger.info(f"Generated strategy created: {self.strategy_id}")
    
    def should_enter_trade(self, signal: TradingSignal, context: MarketContext) -> bool:
        """Determine if should enter trade using generated strategy logic."""
        try:
            # Get current features
            features = self.feature_engineer.extract_features(signal.symbol)
            if not features:
                return False
            
            # Use ML model if trained
            if self.is_trained and self.ml_model:
                return self._ml_entry_decision(features, context)
            
            # Use rule-based logic from gene
            return self._rule_based_entry_decision(features, signal, context)
            
        except Exception as e:
            logger.error(f"Error in generated strategy entry decision: {e}")
            return False
    
    def _ml_entry_decision(self, features: MarketFeatures, context: MarketContext) -> bool:
        """Make entry decision using trained ML model."""
        try:
            # Prepare feature vector
            feature_vector = self._prepare_feature_vector(features, context)
            if feature_vector is None:
                return False
            
            # Scale features
            feature_vector_scaled = self.scaler.transform([feature_vector])
            
            # Predict
            prediction = self.ml_model.predict(feature_vector_scaled)[0]
            confidence = self.ml_model.predict_proba(feature_vector_scaled)[0].max()
            
            # Entry decision based on prediction and confidence
            return prediction == 1 and confidence > 0.6  # Buy signal with high confidence
            
        except Exception as e:
            logger.error(f"Error in ML entry decision: {e}")
            return False
    
    def _rule_based_entry_decision(self, features: MarketFeatures, signal: TradingSignal, context: MarketContext) -> bool:
        """Make entry decision using rule-based logic from gene."""
        try:
            conditions_met = []
            
            # Check entry conditions based on gene
            for indicator in self.gene.entry_indicators:
                threshold = self.gene.entry_thresholds.get(indicator, 0.5)
                
                if indicator == "rsi":
                    rsi = features.technical_features.get("rsi", 50)
                    if signal.signal_type.value == "BUY":
                        conditions_met.append(rsi < threshold * 100)  # Oversold
                    else:
                        conditions_met.append(rsi > (1 - threshold) * 100)  # Overbought
                
                elif indicator == "macd_bullish":
                    macd_bullish = features.technical_features.get("macd_bullish", 0)
                    conditions_met.append(macd_bullish > threshold)
                
                elif indicator == "bb_position":
                    bb_pos = features.technical_features.get("bb_position", 0.5)
                    if signal.signal_type.value == "BUY":
                        conditions_met.append(bb_pos < threshold)  # Near lower band
                    else:
                        conditions_met.append(bb_pos > (1 - threshold))  # Near upper band
                
                elif indicator == "volume_ratio":
                    vol_ratio = features.volume_features.get("volume_ratio_20", 1.0)
                    conditions_met.append(vol_ratio > threshold)
                
                elif indicator == "volatility":
                    vol = features.volatility_features.get("volatility_20d", 0.2)
                    min_vol, max_vol = self.gene.preferred_volatility
                    conditions_met.append(min_vol <= vol <= max_vol)
            
            # Apply logic
            if self.gene.entry_logic == "AND":
                return all(conditions_met) if conditions_met else False
            elif self.gene.entry_logic == "OR":
                return any(conditions_met) if conditions_met else False
            else:  # WEIGHTED
                return sum(conditions_met) / len(conditions_met) > 0.6 if conditions_met else False
            
        except Exception as e:
            logger.error(f"Error in rule-based entry decision: {e}")
            return False
    
    def calculate_position_size(self, context: MarketContext) -> int:
        """Calculate position size using gene's method."""
        try:
            base_capital = context.available_capital * self.allocation
            
            if self.gene.position_size_method == "fixed":
                position_value = base_capital * Decimal(str(self.gene.base_position_size))
            
            elif self.gene.position_size_method == "volatility_adjusted":
                # Adjust for volatility
                symbol_features = self.feature_engineer.extract_features(context.symbol)
                if symbol_features:
                    volatility = symbol_features.volatility_features.get("volatility_20d", 0.2)
                    vol_adjustment = min(0.2 / volatility, 2.0) if volatility > 0 else 1.0
                    position_value = base_capital * Decimal(str(self.gene.base_position_size * vol_adjustment))
                else:
                    position_value = base_capital * Decimal(str(self.gene.base_position_size))
            
            elif self.gene.position_size_method == "kelly":
                # Simplified Kelly criterion
                win_rate = self.performance.win_rate
                avg_win = float(self.performance.avg_win) if self.performance.avg_win > 0 else 0.02
                avg_loss = float(self.performance.avg_loss) if self.performance.avg_loss > 0 else 0.02
                
                if avg_loss > 0:
                    kelly_fraction = (win_rate * avg_win - (1 - win_rate) * avg_loss) / avg_win
                    kelly_fraction = max(0.01, min(0.25, kelly_fraction))  # Limit Kelly fraction
                    position_value = base_capital * Decimal(str(kelly_fraction))
                else:
                    position_value = base_capital * Decimal(str(self.gene.base_position_size))
            
            else:
                position_value = base_capital * Decimal(str(self.gene.base_position_size))
            
            quantity = int(position_value / context.current_price)
            return max(1, quantity)
            
        except Exception as e:
            logger.error(f"Error calculating position size: {e}")
            return 1
    
    def get_exit_conditions(self, context: MarketContext) -> List:
        """Get exit conditions from gene."""
        conditions = []
        
        # Standard stop loss and take profit
        conditions.extend(super().get_exit_conditions(context))
        
        # Time-based exit
        if hasattr(self.gene, 'max_hold_time'):
            conditions.append({
                'type': 'time_based',
                'max_hours': self.gene.max_hold_time
            })
        
        return conditions
    
    def train_ml_model(self, training_data: List[Dict]) -> bool:
        """Train ML model on historical data."""
        try:
            if len(training_data) < 100:
                logger.warning("Insufficient training data for ML model")
                return False
            
            # Prepare training data
            X, y = self._prepare_training_data(training_data)
            if X is None or len(X) == 0:
                return False
            
            # Scale features
            X_scaled = self.scaler.fit_transform(X)
            
            # Train model
            self.ml_model = GradientBoostingClassifier(
                n_estimators=100,
                max_depth=6,
                learning_rate=0.1,
                random_state=42
            )
            
            self.ml_model.fit(X_scaled, y)
            
            # Evaluate model
            cv_scores = cross_val_score(self.ml_model, X_scaled, y, cv=5)
            avg_score = cv_scores.mean()
            
            if avg_score > 0.55:  # Better than random
                self.is_trained = True
                logger.info(f"ML model trained successfully. CV Score: {avg_score:.3f}")
                return True
            else:
                logger.warning(f"ML model performance too low: {avg_score:.3f}")
                return False
            
        except Exception as e:
            logger.error(f"Error training ML model: {e}")
            return False
    
    def _prepare_training_data(self, training_data: List[Dict]) -> Tuple[Optional[np.ndarray], Optional[np.ndarray]]:
        """Prepare training data for ML model."""
        try:
            X = []
            y = []
            
            for data_point in training_data:
                features = data_point.get('features')
                outcome = data_point.get('outcome')  # 1 for profitable, 0 for unprofitable
                
                if features and outcome is not None:
                    feature_vector = self._prepare_feature_vector(features, None)
                    if feature_vector is not None:
                        X.append(feature_vector)
                        y.append(outcome)
            
            if len(X) == 0:
                return None, None
            
            return np.array(X), np.array(y)
            
        except Exception as e:
            logger.error(f"Error preparing training data: {e}")
            return None, None
    
    def _prepare_feature_vector(self, features: MarketFeatures, context: Optional[MarketContext]) -> Optional[np.ndarray]:
        """Prepare feature vector for ML model."""
        try:
            feature_vector = []
            
            # Add relevant features based on gene
            for indicator in self.gene.entry_indicators:
                if indicator == "rsi":
                    feature_vector.append(features.technical_features.get("rsi", 50) / 100.0)
                elif indicator == "macd_bullish":
                    feature_vector.append(features.technical_features.get("macd_bullish", 0))
                elif indicator == "bb_position":
                    feature_vector.append(features.technical_features.get("bb_position", 0.5))
                elif indicator == "volume_ratio":
                    feature_vector.append(features.volume_features.get("volume_ratio_20", 1.0))
                elif indicator == "volatility":
                    feature_vector.append(features.volatility_features.get("volatility_20d", 0.2))
            
            # Add price features
            feature_vector.extend([
                features.price_features.get("return_5d", 0),
                features.price_features.get("return_20d", 0),
                features.price_features.get("momentum_10d", 0),
            ])
            
            # Add temporal features
            feature_vector.extend([
                features.temporal_features.get("hour", 12) / 24.0,
                features.temporal_features.get("is_market_open", 0),
                features.temporal_features.get("is_friday", 0),
            ])
            
            # Add regime features
            feature_vector.extend([
                features.regime_features.get("trend_regime", 0),
                features.regime_features.get("vol_regime", 0),
                features.regime_features.get("momentum_regime", 0),
            ])
            
            return np.array(feature_vector, dtype=np.float32)
            
        except Exception as e:
            logger.error(f"Error preparing feature vector: {e}")
            return None


class AIStrategyGenerator:
    """
    AI-powered strategy generator using genetic algorithms and machine learning.
    Creates, evolves, and optimizes trading strategies automatically.
    """
    
    def __init__(self, feature_engineer: FeatureEngineer):
        self.feature_engineer = feature_engineer
        self.population: List[StrategyGene] = []
        self.population_size = 50
        self.generation = 0
        self.elite_size = 10
        self.mutation_rate = 0.1
        self.crossover_rate = 0.7
        
        # Available indicators for strategy generation
        self.available_indicators = [
            "rsi", "macd_bullish", "bb_position", "volume_ratio", 
            "volatility", "momentum", "trend_regime", "price_vs_ma"
        ]
        
        # Strategy performance tracking
        self.strategy_performance: Dict[str, StrategyPerformance] = {}
        self.best_strategies: List[StrategyGene] = []
        
        logger.info("AI Strategy Generator initialized")
    
    def initialize_population(self) -> None:
        """Initialize random population of strategy genes."""
        self.population = []
        
        for _ in range(self.population_size):
            gene = self._create_random_gene()
            self.population.append(gene)
        
        logger.info(f"Initialized population of {self.population_size} strategies")
    
    def _create_random_gene(self) -> StrategyGene:
        """Create a random strategy gene."""
        # Random selection of indicators
        num_indicators = random.randint(2, 5)
        entry_indicators = random.sample(self.available_indicators, num_indicators)
        
        # Random thresholds
        entry_thresholds = {}
        for indicator in entry_indicators:
            if indicator == "rsi":
                entry_thresholds[indicator] = random.uniform(0.2, 0.4)  # For oversold
            elif indicator == "bb_position":
                entry_thresholds[indicator] = random.uniform(0.1, 0.3)  # Near bands
            elif indicator == "volume_ratio":
                entry_thresholds[indicator] = random.uniform(1.2, 3.0)  # Above average
            else:
                entry_thresholds[indicator] = random.uniform(0.3, 0.7)
        
        gene = StrategyGene(
            entry_indicators=entry_indicators,
            entry_thresholds=entry_thresholds,
            entry_logic=random.choice(["AND", "OR", "WEIGHTED"]),
            stop_loss_pct=random.uniform(0.01, 0.05),
            take_profit_pct=random.uniform(0.02, 0.08),
            position_size_method=random.choice(["fixed", "volatility_adjusted", "kelly"]),
            base_position_size=random.uniform(0.05, 0.2),
            max_positions=random.randint(1, 5),
            max_hold_time=random.randint(2, 48),
            preferred_volatility=(random.uniform(0.005, 0.02), random.uniform(0.03, 0.1))
        )
        
        return gene
    
    def evolve_population(self, performance_data: Dict[str, StrategyPerformance]) -> None:
        """Evolve the population based on performance."""
        try:
            # Update fitness scores
            for i, gene in enumerate(self.population):
                strategy_id = f"generated_{i}"
                if strategy_id in performance_data:
                    perf = performance_data[strategy_id]
                    gene.fitness_score = perf.calculate_fitness()
                    gene.sharpe_ratio = perf.sharpe_ratio
                    gene.win_rate = perf.win_rate
                    gene.total_trades = perf.total_trades
            
            # Sort by fitness
            self.population.sort(key=lambda g: g.fitness_score, reverse=True)
            
            # Keep elite strategies
            new_population = self.population[:self.elite_size].copy()
            
            # Generate offspring
            while len(new_population) < self.population_size:
                if random.random() < self.crossover_rate:
                    # Crossover
                    parent1 = self._tournament_selection()
                    parent2 = self._tournament_selection()
                    offspring = self._crossover(parent1, parent2)
                else:
                    # Mutation only
                    parent = self._tournament_selection()
                    offspring = self._mutate(parent)
                
                new_population.append(offspring)
            
            self.population = new_population
            self.generation += 1
            
            # Update best strategies
            self.best_strategies = self.population[:5].copy()
            
            logger.info(f"Evolution completed. Generation: {self.generation}, "
                       f"Best fitness: {self.population[0].fitness_score:.3f}")
            
        except Exception as e:
            logger.error(f"Error evolving population: {e}")
    
    def _tournament_selection(self, tournament_size: int = 3) -> StrategyGene:
        """Select parent using tournament selection."""
        tournament = random.sample(self.population, min(tournament_size, len(self.population)))
        return max(tournament, key=lambda g: g.fitness_score)
    
    def _crossover(self, parent1: StrategyGene, parent2: StrategyGene) -> StrategyGene:
        """Create offspring through crossover."""
        offspring = StrategyGene()
        
        # Mix indicators
        all_indicators = list(set(parent1.entry_indicators + parent2.entry_indicators))
        offspring.entry_indicators = random.sample(all_indicators, min(len(all_indicators), 5))
        
        # Mix thresholds
        for indicator in offspring.entry_indicators:
            if indicator in parent1.entry_thresholds and indicator in parent2.entry_thresholds:
                offspring.entry_thresholds[indicator] = random.choice([
                    parent1.entry_thresholds[indicator],
                    parent2.entry_thresholds[indicator],
                    (parent1.entry_thresholds[indicator] + parent2.entry_thresholds[indicator]) / 2
                ])
            elif indicator in parent1.entry_thresholds:
                offspring.entry_thresholds[indicator] = parent1.entry_thresholds[indicator]
            elif indicator in parent2.entry_thresholds:
                offspring.entry_thresholds[indicator] = parent2.entry_thresholds[indicator]
        
        # Mix other parameters
        offspring.entry_logic = random.choice([parent1.entry_logic, parent2.entry_logic])
        offspring.stop_loss_pct = random.choice([parent1.stop_loss_pct, parent2.stop_loss_pct])
        offspring.take_profit_pct = random.choice([parent1.take_profit_pct, parent2.take_profit_pct])
        offspring.position_size_method = random.choice([parent1.position_size_method, parent2.position_size_method])
        offspring.base_position_size = (parent1.base_position_size + parent2.base_position_size) / 2
        offspring.max_positions = random.choice([parent1.max_positions, parent2.max_positions])
        offspring.max_hold_time = random.choice([parent1.max_hold_time, parent2.max_hold_time])
        
        return offspring
    
    def _mutate(self, parent: StrategyGene) -> StrategyGene:
        """Create offspring through mutation."""
        offspring = StrategyGene(
            entry_indicators=parent.entry_indicators.copy(),
            entry_thresholds=parent.entry_thresholds.copy(),
            entry_logic=parent.entry_logic,
            stop_loss_pct=parent.stop_loss_pct,
            take_profit_pct=parent.take_profit_pct,
            position_size_method=parent.position_size_method,
            base_position_size=parent.base_position_size,
            max_positions=parent.max_positions,
            max_hold_time=parent.max_hold_time,
            preferred_volatility=parent.preferred_volatility
        )
        
        offspring.mutate(self.mutation_rate)
        return offspring
    
    def generate_strategies(self, num_strategies: int = 5) -> List[GeneratedStrategy]:
        """Generate new trading strategies."""
        try:
            if not self.population:
                self.initialize_population()
            
            strategies = []
            
            # Use best genes from population
            best_genes = sorted(self.population, key=lambda g: g.fitness_score, reverse=True)[:num_strategies]
            
            for i, gene in enumerate(best_genes):
                strategy_config = StrategyConfig(
                    strategy_id=f"ai_generated_{self.generation}_{i}",
                    strategy_type="ai_generated",
                    enabled=True,
                    allocation=Decimal('0.1'),  # 10% allocation
                    parameters={}
                )
                
                strategy = GeneratedStrategy(strategy_config, gene, self.feature_engineer)
                strategies.append(strategy)
            
            logger.info(f"Generated {len(strategies)} new AI strategies")
            return strategies
            
        except Exception as e:
            logger.error(f"Error generating strategies: {e}")
            return []
    
    def get_best_strategies(self, top_n: int = 3) -> List[StrategyGene]:
        """Get the best performing strategies."""
        if not self.population:
            return []
        
        sorted_population = sorted(self.population, key=lambda g: g.fitness_score, reverse=True)
        return sorted_population[:top_n]
    
    def save_population(self, filepath: str) -> None:
        """Save current population to file."""
        try:
            population_data = []
            for gene in self.population:
                gene_dict = {
                    'entry_indicators': gene.entry_indicators,
                    'entry_thresholds': gene.entry_thresholds,
                    'entry_logic': gene.entry_logic,
                    'stop_loss_pct': gene.stop_loss_pct,
                    'take_profit_pct': gene.take_profit_pct,
                    'position_size_method': gene.position_size_method,
                    'base_position_size': gene.base_position_size,
                    'max_positions': gene.max_positions,
                    'max_hold_time': gene.max_hold_time,
                    'fitness_score': gene.fitness_score,
                    'sharpe_ratio': gene.sharpe_ratio,
                    'win_rate': gene.win_rate,
                    'total_trades': gene.total_trades
                }
                population_data.append(gene_dict)
            
            with open(filepath, 'w') as f:
                json.dump({
                    'generation': self.generation,
                    'population': population_data
                }, f, indent=2)
            
            logger.info(f"Population saved to {filepath}")
            
        except Exception as e:
            logger.error(f"Error saving population: {e}")
    
    def load_population(self, filepath: str) -> None:
        """Load population from file."""
        try:
            with open(filepath, 'r') as f:
                data = json.load(f)
            
            self.generation = data.get('generation', 0)
            population_data = data.get('population', [])
            
            self.population = []
            for gene_dict in population_data:
                gene = StrategyGene(
                    entry_indicators=gene_dict['entry_indicators'],
                    entry_thresholds=gene_dict['entry_thresholds'],
                    entry_logic=gene_dict['entry_logic'],
                    stop_loss_pct=gene_dict['stop_loss_pct'],
                    take_profit_pct=gene_dict['take_profit_pct'],
                    position_size_method=gene_dict['position_size_method'],
                    base_position_size=gene_dict['base_position_size'],
                    max_positions=gene_dict['max_positions'],
                    max_hold_time=gene_dict['max_hold_time'],
                    fitness_score=gene_dict.get('fitness_score', 0.0),
                    sharpe_ratio=gene_dict.get('sharpe_ratio', 0.0),
                    win_rate=gene_dict.get('win_rate', 0.0),
                    total_trades=gene_dict.get('total_trades', 0)
                )
                self.population.append(gene)
            
            logger.info(f"Population loaded from {filepath}. Generation: {self.generation}")
            
        except Exception as e:
            logger.error(f"Error loading population: {e}")


# Global strategy generator instance
ai_strategy_generator = None