"""
Core data models for the trading bot.
Defines the main entities used throughout the system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Dict, List, Optional, Any
import uuid


class Exchange(Enum):
    """Indian stock exchanges."""
    NSE = "NSE"
    BSE = "BSE"


class OrderSide(Enum):
    """Order side (buy/sell)."""
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    """Order types supported."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP_LOSS = "STOP_LOSS"
    STOP_LOSS_MARKET = "STOP_LOSS_MARKET"


class OrderStatus(Enum):
    """Order status states."""
    PENDING = "PENDING"
    OPEN = "OPEN"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class SignalType(Enum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TradeSide(Enum):
    """Trade side for executed trades."""
    BUY = "BUY"
    SELL = "SELL"


@dataclass
class MarketTick:
    """Real-time market data tick."""
    symbol: str
    exchange: Exchange
    timestamp: datetime
    price: Decimal
    volume: int
    bid_price: Decimal
    ask_price: Decimal
    bid_size: int
    ask_size: int
    
    def __post_init__(self):
        """Validate tick data."""
        if self.price <= 0:
            raise ValueError("Price must be positive")
        if self.volume < 0:
            raise ValueError("Volume cannot be negative")


@dataclass
class OHLC:
    """OHLC (Open, High, Low, Close) data for a time period."""
    timestamp: datetime
    open_price: Decimal
    high_price: Decimal
    low_price: Decimal
    close_price: Decimal
    volume: int
    
    def __post_init__(self):
        """Validate OHLC data."""
        prices = [self.open_price, self.high_price, self.low_price, self.close_price]
        if any(p <= 0 for p in prices):
            raise ValueError("All prices must be positive")
        if self.high_price < max(self.open_price, self.close_price):
            raise ValueError("High price must be >= open and close prices")
        if self.low_price > min(self.open_price, self.close_price):
            raise ValueError("Low price must be <= open and close prices")


@dataclass
class MarketData:
    """Aggregated market data for a symbol."""
    symbol: str
    exchange: Exchange
    ohlc_1min: List[OHLC] = field(default_factory=list)
    ohlc_5min: List[OHLC] = field(default_factory=list)
    ohlc_15min: List[OHLC] = field(default_factory=list)
    ohlc_1hour: List[OHLC] = field(default_factory=list)
    current_tick: Optional[MarketTick] = None
    last_updated: datetime = field(default_factory=datetime.now)


@dataclass
class TradingSignal:
    """Trading signal generated by technical analysis."""
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    signal_type: SignalType = SignalType.HOLD
    strength: float = 0.0  # 0.0 to 1.0
    indicators_used: List[str] = field(default_factory=list)
    timestamp: datetime = field(default_factory=datetime.now)
    price_target: Optional[Decimal] = None
    confidence: float = 0.0  # 0.0 to 1.0
    
    def __post_init__(self):
        """Validate signal data."""
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError("Signal strength must be between 0.0 and 1.0")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")


@dataclass
class TradeDecision:
    """Trading decision made by strategy engine."""
    decision_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    action: OrderSide = OrderSide.BUY
    quantity: int = 0
    order_type: OrderType = OrderType.MARKET
    price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    strategy_id: str = ""
    timestamp: datetime = field(default_factory=datetime.now)
    
    def __post_init__(self):
        """Validate trade decision."""
        if self.quantity <= 0:
            raise ValueError("Quantity must be positive")
        if self.order_type == OrderType.LIMIT and self.price is None:
            raise ValueError("Limit orders must have a price")


@dataclass
class Order:
    """Order placed with broker."""
    order_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    broker_order_id: Optional[str] = None
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    quantity: int = 0
    order_type: OrderType = OrderType.MARKET
    price: Optional[Decimal] = None
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: int = 0
    average_price: Decimal = Decimal('0')
    timestamp: datetime = field(default_factory=datetime.now)
    last_updated: datetime = field(default_factory=datetime.now)
    
    @property
    def is_filled(self) -> bool:
        """Check if order is completely filled."""
        return self.status == OrderStatus.FILLED
    
    @property
    def remaining_quantity(self) -> int:
        """Get remaining unfilled quantity."""
        return self.quantity - self.filled_quantity


@dataclass
class Position:
    """Trading position in a symbol."""
    symbol: str
    quantity: int  # Positive for long, negative for short
    average_price: Decimal
    current_price: Decimal = Decimal('0')
    unrealized_pnl: Decimal = Decimal('0')
    realized_pnl: Decimal = Decimal('0')
    timestamp: datetime = field(default_factory=datetime.now)
    last_updated: datetime = field(default_factory=datetime.now)
    
    @property
    def is_long(self) -> bool:
        """Check if position is long."""
        return self.quantity > 0
    
    @property
    def is_short(self) -> bool:
        """Check if position is short."""
        return self.quantity < 0
    
    @property
    def market_value(self) -> Decimal:
        """Calculate current market value of position."""
        return abs(self.quantity) * self.current_price
    
    def update_pnl(self, current_price: Decimal) -> None:
        """Update P&L based on current market price."""
        self.current_price = current_price
        if self.quantity != 0:
            self.unrealized_pnl = (current_price - self.average_price) * self.quantity
        self.last_updated = datetime.now()


@dataclass
class Trade:
    """Executed trade record."""
    trade_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str = ""
    side: TradeSide = TradeSide.BUY
    quantity: int = 0
    price: Decimal = Decimal('0')
    timestamp: datetime = field(default_factory=datetime.now)
    strategy_id: str = ""
    commission: Decimal = Decimal('0')
    order_id: str = ""
    
    @property
    def gross_value(self) -> Decimal:
        """Calculate gross trade value."""
        return self.quantity * self.price
    
    @property
    def net_value(self) -> Decimal:
        """Calculate net trade value after commission."""
        return self.gross_value - self.commission


@dataclass
class AccountInfo:
    """Broker account information."""
    account_id: str = ""
    available_margin: Decimal = Decimal('0')
    used_margin: Decimal = Decimal('0')
    total_balance: Decimal = Decimal('0')
    day_pnl: Decimal = Decimal('0')
    total_pnl: Decimal = Decimal('0')
    last_updated: datetime = field(default_factory=datetime.now)
    
    @property
    def buying_power(self) -> Decimal:
        """Calculate available buying power."""
        return self.available_margin


@dataclass
class RiskLimits:
    """Risk management limits."""
    max_position_size: Decimal = Decimal('100000')  # Max position value
    max_daily_loss: Decimal = Decimal('10000')      # Max daily loss
    max_portfolio_exposure: Decimal = Decimal('500000')  # Max total exposure
    max_positions_per_symbol: int = 1
    max_total_positions: int = 10
    sebi_position_limits: Dict[str, Decimal] = field(default_factory=dict)
    
    def validate_position_size(self, symbol: str, value: Decimal) -> bool:
        """Validate if position size is within limits."""
        if value > self.max_position_size:
            return False
        
        sebi_limit = self.sebi_position_limits.get(symbol)
        if sebi_limit and value > sebi_limit:
            return False
        
        return True


@dataclass
class TickData:
    """Tick data model for real-time market data."""
    instrument_token: str  # str to match Angel One token format
    timestamp: datetime
    last_price: float
    volume: int
    bid_price: float = 0.0
    ask_price: float = 0.0
    bid_quantity: int = 0
    ask_quantity: int = 0
    open_price: float = 0.0
    high_price: float = 0.0
    low_price: float = 0.0
    close_price: float = 0.0


@dataclass
class OHLCData:
    """OHLC data model for candlestick data."""
    instrument_token: str  # str to match Angel One token format
    timestamp: datetime
    open_price: float
    high_price: float
    low_price: float
    close_price: float
    volume: int
    timeframe: str = "1m"


@dataclass
class Signal:
    """Trading signal data model."""
    symbol: str
    action: str  # BUY, SELL, HOLD
    price: float
    quantity: int = 0
    confidence: float = 0.5
    timestamp: datetime = None
    strategy: str = ""
    strategy_name: str = ""
    reason: str = ""
    strength: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    target: Optional[float] = None
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class IndicatorValues:
    """Technical indicator values."""
    timestamp: datetime = field(default_factory=datetime.now)
    sma_20: Optional[Decimal] = None
    sma_50: Optional[Decimal] = None
    ema_12: Optional[Decimal] = None
    ema_26: Optional[Decimal] = None
    rsi: Optional[float] = None
    macd_line: Optional[Decimal] = None
    macd_signal: Optional[Decimal] = None
    macd_histogram: Optional[Decimal] = None
    bb_upper: Optional[Decimal] = None
    bb_middle: Optional[Decimal] = None
    bb_lower: Optional[Decimal] = None
    
    def has_sufficient_data(self) -> bool:
        """Check if we have sufficient indicator data for analysis."""
        return any([
            self.sma_20 is not None,
            self.ema_12 is not None,
            self.rsi is not None,
            self.macd_line is not None
        ])